apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: wordpress-ingress
  namespace: dev

spec:
  rules:

  - host: admin.seusite.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-admin
            port:
              number: 80

  - host: seusite.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: wordpress-frontend
            port:
              number: 80